# Server
server.port=8080
spring.application.name=Fedotov

# Database - теперь порт 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Swagger UI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.packages-to-scan=ru.rksp.Fedotov
springdoc.paths-to-match=/**

# OpenAPI Info
springdoc.api-docs.info.title=Fedotov API
springdoc.api-docs.info.description=Лабораторная работа №1
springdoc.api-docs.info.version=1.0.0
springdoc.api-docs.info.contact.name=Fedotov
